<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'security.access_map' shared service.

include_once $this->targetDirs[3].'/vendor/symfony/security-http/AccessMapInterface.php';
include_once $this->targetDirs[3].'/vendor/symfony/security-http/AccessMap.php';
include_once $this->targetDirs[3].'/vendor/symfony/http-foundation/RequestMatcherInterface.php';
include_once $this->targetDirs[3].'/vendor/symfony/http-foundation/RequestMatcher.php';

$this->privates['security.access_map'] = $instance = new \Symfony\Component\Security\Http\AccessMap();

$instance->add(new \Symfony\Component\HttpFoundation\RequestMatcher('^/login'), [0 => 'IS_AUTHENTICATED_ANONYMOUSLY'], NULL);
$instance->add(new \Symfony\Component\HttpFoundation\RequestMatcher('^/turma/new'), [0 => 'ROLE_COORDENADOR'], NULL);
$instance->add(new \Symfony\Component\HttpFoundation\RequestMatcher('^/turma/edit'), [0 => 'ROLE_COORDENADOR'], NULL);
$instance->add(new \Symfony\Component\HttpFoundation\RequestMatcher('^/escola/new'), [0 => 'ROLE_COORDENADOR'], NULL);
$instance->add(new \Symfony\Component\HttpFoundation\RequestMatcher('^/escola/edit'), [0 => 'ROLE_COORDENADOR'], NULL);
$instance->add(new \Symfony\Component\HttpFoundation\RequestMatcher('^/catequizando'), [0 => 'ROLE_CATEQUISTA'], NULL);
$instance->add(new \Symfony\Component\HttpFoundation\RequestMatcher('^/turma'), [0 => 'ROLE_CATEQUISTA'], NULL);
$instance->add(new \Symfony\Component\HttpFoundation\RequestMatcher('^/escola'), [0 => 'ROLE_CATEQUISTA'], NULL);

return $instance;
