<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.0Msc3Ob' shared service.

return $this->privates['.service_locator.0Msc3Ob'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'turmaRepository' => ['privates', 'App\\Repository\\TurmaRepository', 'getTurmaRepositoryService.php', true],
]);
