<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.7gxtins' shared service.

return $this->privates['.service_locator.7gxtins'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'catequistum' => ['privates', '.errored..service_locator.7gxtins.App\\Entity\\Catequista', NULL, 'Cannot autowire service ".service_locator.7gxtins": it references class "App\\Entity\\Catequista" but no such service exists.'],
]);
