<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.L6qFtBy' shared service.

return $this->privates['.service_locator.L6qFtBy'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'escola' => ['privates', '.errored..service_locator.L6qFtBy.App\\Entity\\Escola', NULL, 'Cannot autowire service ".service_locator.L6qFtBy": it references class "App\\Entity\\Escola" but no such service exists.'],
]);
