<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerZTCM96U\srcApp_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerZTCM96U/srcApp_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerZTCM96U.legacy');

    return;
}

if (!\class_exists(srcApp_KernelProdContainer::class, false)) {
    \class_alias(\ContainerZTCM96U\srcApp_KernelProdContainer::class, srcApp_KernelProdContainer::class, false);
}

return new \ContainerZTCM96U\srcApp_KernelProdContainer([
    'container.build_hash' => 'ZTCM96U',
    'container.build_id' => '57a44caa',
    'container.build_time' => 1554777330,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerZTCM96U');
