<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.qIeRiVK' shared service.

return $this->privates['.service_locator.qIeRiVK'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'escolaRepository' => ['privates', 'App\\Repository\\EscolaRepository', 'getEscolaRepositoryService.php', true],
]);
