<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.PGqdrHh' shared service.

return $this->privates['.service_locator.PGqdrHh'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'catequizandoRepository' => ['privates', 'App\\Repository\\CatequizandoRepository', 'getCatequizandoRepositoryService.php', true],
]);
