<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.cl39yVF' shared service.

return $this->privates['.service_locator.cl39yVF'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'turma' => ['privates', '.errored..service_locator.cl39yVF.App\\Entity\\Turma', NULL, 'Cannot autowire service ".service_locator.cl39yVF": it references class "App\\Entity\\Turma" but no such service exists.'],
]);
