<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.IY_taS0' shared service.

return $this->privates['.service_locator.IY_taS0'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'catequizando' => ['privates', '.errored..service_locator.IY_taS0.App\\Entity\\Catequizando', NULL, 'Cannot autowire service ".service_locator.IY_taS0": it references class "App\\Entity\\Catequizando" but no such service exists.'],
]);
