<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container1OyVZZx\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container1OyVZZx/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container1OyVZZx.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container1OyVZZx\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \Container1OyVZZx\srcApp_KernelDevDebugContainer([
    'container.build_hash' => '1OyVZZx',
    'container.build_id' => 'a325e0a7',
    'container.build_time' => 1554778677,
], __DIR__.\DIRECTORY_SEPARATOR.'Container1OyVZZx');
