<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Catequizando extends \App\Entity\Catequizando implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Catequizando' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Catequizando' . "\0" . 'nome', '' . "\0" . 'App\\Entity\\Catequizando' . "\0" . 'sexo', '' . "\0" . 'App\\Entity\\Catequizando' . "\0" . 'dataNascimento', '' . "\0" . 'App\\Entity\\Catequizando' . "\0" . 'naturalidade', '' . "\0" . 'App\\Entity\\Catequizando' . "\0" . 'endereco', '' . "\0" . 'App\\Entity\\Catequizando' . "\0" . 'telefone', '' . "\0" . 'App\\Entity\\Catequizando' . "\0" . 'batizado', '' . "\0" . 'App\\Entity\\Catequizando' . "\0" . 'comprovanteBatizado', '' . "\0" . 'App\\Entity\\Catequizando' . "\0" . 'nomePai', '' . "\0" . 'App\\Entity\\Catequizando' . "\0" . 'nomeMae', '' . "\0" . 'App\\Entity\\Catequizando' . "\0" . 'casado', '' . "\0" . 'App\\Entity\\Catequizando' . "\0" . 'comprovanteCasamento', '' . "\0" . 'App\\Entity\\Catequizando' . "\0" . 'eucaristia', '' . "\0" . 'App\\Entity\\Catequizando' . "\0" . 'comprovanteEucaristia', '' . "\0" . 'App\\Entity\\Catequizando' . "\0" . 'documento', '' . "\0" . 'App\\Entity\\Catequizando' . "\0" . 'telefonePai', '' . "\0" . 'App\\Entity\\Catequizando' . "\0" . 'telefoneMae', '' . "\0" . 'App\\Entity\\Catequizando' . "\0" . 'nomePadrinhoCrisma', '' . "\0" . 'App\\Entity\\Catequizando' . "\0" . 'telPadrinho', '' . "\0" . 'App\\Entity\\Catequizando' . "\0" . 'enderecoPadrinho', '' . "\0" . 'App\\Entity\\Catequizando' . "\0" . 'cidadeCatequizando', '' . "\0" . 'App\\Entity\\Catequizando' . "\0" . 'cidadePadrinho', '' . "\0" . 'App\\Entity\\Catequizando' . "\0" . 'turma', '' . "\0" . 'App\\Entity\\Catequizando' . "\0" . 'pendencias'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Catequizando' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Catequizando' . "\0" . 'nome', '' . "\0" . 'App\\Entity\\Catequizando' . "\0" . 'sexo', '' . "\0" . 'App\\Entity\\Catequizando' . "\0" . 'dataNascimento', '' . "\0" . 'App\\Entity\\Catequizando' . "\0" . 'naturalidade', '' . "\0" . 'App\\Entity\\Catequizando' . "\0" . 'endereco', '' . "\0" . 'App\\Entity\\Catequizando' . "\0" . 'telefone', '' . "\0" . 'App\\Entity\\Catequizando' . "\0" . 'batizado', '' . "\0" . 'App\\Entity\\Catequizando' . "\0" . 'comprovanteBatizado', '' . "\0" . 'App\\Entity\\Catequizando' . "\0" . 'nomePai', '' . "\0" . 'App\\Entity\\Catequizando' . "\0" . 'nomeMae', '' . "\0" . 'App\\Entity\\Catequizando' . "\0" . 'casado', '' . "\0" . 'App\\Entity\\Catequizando' . "\0" . 'comprovanteCasamento', '' . "\0" . 'App\\Entity\\Catequizando' . "\0" . 'eucaristia', '' . "\0" . 'App\\Entity\\Catequizando' . "\0" . 'comprovanteEucaristia', '' . "\0" . 'App\\Entity\\Catequizando' . "\0" . 'documento', '' . "\0" . 'App\\Entity\\Catequizando' . "\0" . 'telefonePai', '' . "\0" . 'App\\Entity\\Catequizando' . "\0" . 'telefoneMae', '' . "\0" . 'App\\Entity\\Catequizando' . "\0" . 'nomePadrinhoCrisma', '' . "\0" . 'App\\Entity\\Catequizando' . "\0" . 'telPadrinho', '' . "\0" . 'App\\Entity\\Catequizando' . "\0" . 'enderecoPadrinho', '' . "\0" . 'App\\Entity\\Catequizando' . "\0" . 'cidadeCatequizando', '' . "\0" . 'App\\Entity\\Catequizando' . "\0" . 'cidadePadrinho', '' . "\0" . 'App\\Entity\\Catequizando' . "\0" . 'turma', '' . "\0" . 'App\\Entity\\Catequizando' . "\0" . 'pendencias'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Catequizando $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getNome(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNome', []);

        return parent::getNome();
    }

    /**
     * {@inheritDoc}
     */
    public function setNome(string $nome): \App\Entity\Catequizando
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNome', [$nome]);

        return parent::setNome($nome);
    }

    /**
     * {@inheritDoc}
     */
    public function getSexo(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSexo', []);

        return parent::getSexo();
    }

    /**
     * {@inheritDoc}
     */
    public function setSexo(string $sexo): \App\Entity\Catequizando
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSexo', [$sexo]);

        return parent::setSexo($sexo);
    }

    /**
     * {@inheritDoc}
     */
    public function getDataNascimento(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDataNascimento', []);

        return parent::getDataNascimento();
    }

    /**
     * {@inheritDoc}
     */
    public function setDataNascimento(\DateTimeInterface $dataNascimento): \App\Entity\Catequizando
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDataNascimento', [$dataNascimento]);

        return parent::setDataNascimento($dataNascimento);
    }

    /**
     * {@inheritDoc}
     */
    public function getNaturalidade(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNaturalidade', []);

        return parent::getNaturalidade();
    }

    /**
     * {@inheritDoc}
     */
    public function setNaturalidade(string $naturalidade): \App\Entity\Catequizando
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNaturalidade', [$naturalidade]);

        return parent::setNaturalidade($naturalidade);
    }

    /**
     * {@inheritDoc}
     */
    public function getEndereco(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEndereco', []);

        return parent::getEndereco();
    }

    /**
     * {@inheritDoc}
     */
    public function setEndereco(string $endereco): \App\Entity\Catequizando
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEndereco', [$endereco]);

        return parent::setEndereco($endereco);
    }

    /**
     * {@inheritDoc}
     */
    public function getTelefone()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTelefone', []);

        return parent::getTelefone();
    }

    /**
     * {@inheritDoc}
     */
    public function setTelefone($telefone)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTelefone', [$telefone]);

        return parent::setTelefone($telefone);
    }

    /**
     * {@inheritDoc}
     */
    public function getBatizado(): ?bool
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBatizado', []);

        return parent::getBatizado();
    }

    /**
     * {@inheritDoc}
     */
    public function setBatizado(bool $batizado): \App\Entity\Catequizando
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBatizado', [$batizado]);

        return parent::setBatizado($batizado);
    }

    /**
     * {@inheritDoc}
     */
    public function getComprovanteBatizado()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getComprovanteBatizado', []);

        return parent::getComprovanteBatizado();
    }

    /**
     * {@inheritDoc}
     */
    public function setComprovanteBatizado($comprovanteBatizado)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setComprovanteBatizado', [$comprovanteBatizado]);

        return parent::setComprovanteBatizado($comprovanteBatizado);
    }

    /**
     * {@inheritDoc}
     */
    public function getNomePai(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNomePai', []);

        return parent::getNomePai();
    }

    /**
     * {@inheritDoc}
     */
    public function setNomePai(string $nomePai): \App\Entity\Catequizando
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNomePai', [$nomePai]);

        return parent::setNomePai($nomePai);
    }

    /**
     * {@inheritDoc}
     */
    public function getNomeMae(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNomeMae', []);

        return parent::getNomeMae();
    }

    /**
     * {@inheritDoc}
     */
    public function setNomeMae(string $nomeMae): \App\Entity\Catequizando
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNomeMae', [$nomeMae]);

        return parent::setNomeMae($nomeMae);
    }

    /**
     * {@inheritDoc}
     */
    public function getCasado(): ?bool
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCasado', []);

        return parent::getCasado();
    }

    /**
     * {@inheritDoc}
     */
    public function setCasado(bool $casado): \App\Entity\Catequizando
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCasado', [$casado]);

        return parent::setCasado($casado);
    }

    /**
     * {@inheritDoc}
     */
    public function getComprovanteCasamento()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getComprovanteCasamento', []);

        return parent::getComprovanteCasamento();
    }

    /**
     * {@inheritDoc}
     */
    public function setComprovanteCasamento($comprovanteCasamento)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setComprovanteCasamento', [$comprovanteCasamento]);

        return parent::setComprovanteCasamento($comprovanteCasamento);
    }

    /**
     * {@inheritDoc}
     */
    public function getTelefonePai()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTelefonePai', []);

        return parent::getTelefonePai();
    }

    /**
     * {@inheritDoc}
     */
    public function setTelefonePai($telefonePai)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTelefonePai', [$telefonePai]);

        return parent::setTelefonePai($telefonePai);
    }

    /**
     * {@inheritDoc}
     */
    public function getTelefoneMae()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTelefoneMae', []);

        return parent::getTelefoneMae();
    }

    /**
     * {@inheritDoc}
     */
    public function setTelefoneMae($telefoneMae)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTelefoneMae', [$telefoneMae]);

        return parent::setTelefoneMae($telefoneMae);
    }

    /**
     * {@inheritDoc}
     */
    public function getNomePadrinhoCrisma(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNomePadrinhoCrisma', []);

        return parent::getNomePadrinhoCrisma();
    }

    /**
     * {@inheritDoc}
     */
    public function setNomePadrinhoCrisma(?string $nomePadrinhoCrisma): \App\Entity\Catequizando
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNomePadrinhoCrisma', [$nomePadrinhoCrisma]);

        return parent::setNomePadrinhoCrisma($nomePadrinhoCrisma);
    }

    /**
     * {@inheritDoc}
     */
    public function getTelPadrinho()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTelPadrinho', []);

        return parent::getTelPadrinho();
    }

    /**
     * {@inheritDoc}
     */
    public function setTelPadrinho($telPadrinho)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTelPadrinho', [$telPadrinho]);

        return parent::setTelPadrinho($telPadrinho);
    }

    /**
     * {@inheritDoc}
     */
    public function getEnderecoPadrinho(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEnderecoPadrinho', []);

        return parent::getEnderecoPadrinho();
    }

    /**
     * {@inheritDoc}
     */
    public function setEnderecoPadrinho(?string $enderecoPadrinho): \App\Entity\Catequizando
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEnderecoPadrinho', [$enderecoPadrinho]);

        return parent::setEnderecoPadrinho($enderecoPadrinho);
    }

    /**
     * {@inheritDoc}
     */
    public function getCidadeCatequizando(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCidadeCatequizando', []);

        return parent::getCidadeCatequizando();
    }

    /**
     * {@inheritDoc}
     */
    public function setCidadeCatequizando(string $cidadeCatequizando): \App\Entity\Catequizando
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCidadeCatequizando', [$cidadeCatequizando]);

        return parent::setCidadeCatequizando($cidadeCatequizando);
    }

    /**
     * {@inheritDoc}
     */
    public function getCidadePadrinho(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCidadePadrinho', []);

        return parent::getCidadePadrinho();
    }

    /**
     * {@inheritDoc}
     */
    public function setCidadePadrinho(?string $cidadePadrinho): \App\Entity\Catequizando
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCidadePadrinho', [$cidadePadrinho]);

        return parent::setCidadePadrinho($cidadePadrinho);
    }

    /**
     * {@inheritDoc}
     */
    public function getTurma(): ?\App\Entity\Turma
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTurma', []);

        return parent::getTurma();
    }

    /**
     * {@inheritDoc}
     */
    public function setTurma(?\App\Entity\Turma $turma): \App\Entity\Catequizando
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTurma', [$turma]);

        return parent::setTurma($turma);
    }

    /**
     * {@inheritDoc}
     */
    public function getPendencias()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPendencias', []);

        return parent::getPendencias();
    }

    /**
     * {@inheritDoc}
     */
    public function setPendencias($pendencias): \App\Entity\Catequizando
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPendencias', [$pendencias]);

        return parent::setPendencias($pendencias);
    }

    /**
     * {@inheritDoc}
     */
    public function getEucaristia()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEucaristia', []);

        return parent::getEucaristia();
    }

    /**
     * {@inheritDoc}
     */
    public function setEucaristia($eucaristia): \App\Entity\Catequizando
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEucaristia', [$eucaristia]);

        return parent::setEucaristia($eucaristia);
    }

    /**
     * {@inheritDoc}
     */
    public function getComprovanteEucaristia()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getComprovanteEucaristia', []);

        return parent::getComprovanteEucaristia();
    }

    /**
     * {@inheritDoc}
     */
    public function setComprovanteEucaristia($comprovanteEucaristia)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setComprovanteEucaristia', [$comprovanteEucaristia]);

        return parent::setComprovanteEucaristia($comprovanteEucaristia);
    }

    /**
     * {@inheritDoc}
     */
    public function getDocumento()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDocumento', []);

        return parent::getDocumento();
    }

    /**
     * {@inheritDoc}
     */
    public function setDocumento($documento)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDocumento', [$documento]);

        return parent::setDocumento($documento);
    }

}
